name: Notify users based on issue labels
permissions:
  issues: read

on:
  issues:
      types: [labeled]

jobs:
  notify:
    runs-on: seqera-cli
    steps:
        - uses: jenschelkopf/issue-label-notification-action@1.3
          with:
            recipients:
              squad-core=@squad-core
              squad-pipelines=@squad-pipelines
              squad-data=@squad-data
              squad-unifiedcompute=@squad-unified-compute
              documentation=@seqera-docs-codeowners
