name: Notify users based on issue labels
permissions:
  issues: read

on:
  issues:
      types: [labeled]

jobs:
  notify:
    runs-on: tower-cli
    steps:
        - uses: jenschelkopf/issue-label-notification-action@1.3
          with:
            recipients:
              squad-strand=@squad-strand
              squad-helix=@squad-helix
              squad-unifiedcompute=@squad-unified-compute
              documentation=@tower-docs-codeowners
