name: Notify users based on issue labels
permissions:
  issues: read

on:
  issues:
      types: [labeled]

jobs:
  notify:
    runs-on: tower-cli
    steps:
        - uses: jenschelkopf/issue-label-notification-action@1.3
          with:
            recipients:
              squad-core=@andrew-dawson-seqera @tcrespog @swampie
              squad-pipelines=@atsyganov @swingingsimian @swampie
              squad-data=@robnewman @t0randr @swampie
              squad-unifiedcompute=@MichaelTansiniSeqera @cristianrcv @swampie
              documentation=@justinegeffen @llewellyn-sl
