name: Notify users based on issue labels
permissions:
  issues: read

on:
  issues:
      types: [labeled]

jobs:
  notify:
    runs-on: tower-cli
    steps:
        - uses: jenschelkopf/issue-label-notification-action@1.3
          with:
            recipients:
              squad-core=@squad-core @swampie
              squad-pipelines=@squad-pipelines @swampie
              squad-data=@squad-data @swampie
              squad-unifiedcompute=@squad-unifiedcompute @swampie
              documentation=@tower-docs-codeowners
